### ISSUE TITLE
Add Typescript Declarations

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [tsouza/jp#3]
It would be radical if I could import this package into a typescript project

**Comment by PhaedrusTheGreek** [comment]
I'd like to be able to do this from a consuming application:

```
    const runner = new ScriptRunner(myInputStream).addGlobal(utils);
    runner.setInlineScript(myStringScript);
    runner.setOutputMode(OutputMode.Object)
    runner.setOutput(myOutputStream)
    runner.run()
```

**Comment by PhaedrusTheGreek** [comment]
![Screen Shot 2020-10-30 at 7 37 10 AM](https://user-images.githubusercontent.com/4387023/97700826-d6fe6900-1a82-11eb-9e13-cbf7f93ed353.png)

**Comment by tsouza** [comment]
This should be addressed in https://github.com/tsouza/jp/pull/5
